### ISSUE TITLE
Belongs_to not updated

### ISSUE THREAD

**Issue by khcr** [elastic/elasticsearch-rails#400]
Hi,
I am currently facing a problem with reindexing my model. When I edit the status of a group, the elasticsearch index is not updated. I tried to add all things possible to my model, but it still doesn't work. Can anyone see the issue ?

``` ruby
class Group
    belongs_to :status, touch: true

    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    after_touch() { __elasticsearch__.index_document }

    mapping do
        indexes :status do
            indexes :name, type: :string, index: :not_analyzed
        end
    end

    def as_indexed_json(options={})
        as_json(only: :name, include: { 
            status: { only: :name },
        })
    end
end

class Status
    include Elasticsearch::Model
    include Elasticsearch::Model::Callbacks

    has_many :cards

    after_update { self.cards.each(&:touch) }
end
```

**Comment by khcr** [comment]
I found out that if I changed the callback, it works:

```ruby
class Group
     
    # normal callback 
    # after_commit lambda { __elasticsearch__.update_document },  on: :update
    after_commit lambda { __elasticsearch__.delete_document ; elasticsearch__.index_document }, on: :update

end
```

So `__elasticsearch__.update_document` seems to have a problem, but if I called it manually afterwards, the index is correctly updated.

**Comment by ggcampinho** [comment]
Same problem here.

I created the method below inside my class and I'm using it to reindex my models if it's needed.
```
def reindex
  __elasticsearch__.update_document_attributes(as_indexed_json)
end
```

I don't think this is the right behaviour to `update_attributes` and not only because of the `belongs_to`, but if you are indexing something there is not an attribute, this will cause errors.

**Comment by khcr** [comment]
Thanks @ggcampinho 
Any answer from the repo's maintainers ?

**Comment by karmi** [comment]
@khcr I'm looking at other tickets today, sorry for the silence.

My first question is if you can verify you have the callback correctly set up between the relationships and it is in fact triggered.

My second question is if you're sure you understand the difference between `update_document` and `update_document_attributes`. The former does check the changed attributes for a reason. There have been couple of fixes for that, please search the issues for details. There might still be a bug somewhere there, but we need a failing test or an executable example for that.

My suggestion is to stay away from the "bundled" callbacks unless this is a toy app. The documentation tries to be quite clear in this regard. In almost any serious application, you should prefer indexing in the background, as the README suggests.

**Comment by khcr** [comment]
Thanks for your answer, you can take your time ! I was just worried if someone was interested.

The purpose of `update_document` is to update the indexed fields in ES when they are modified. But actually, if a `belongs_to` association is modified, the index is not updated as I explained. It is great to check the changed attribute, but we could easily add `belongs_to` support.

I also understand if you want to keep this method simple and I am ready to implement my own indexing. So I should do like ggcampinho suggest ? It seems less optimized because It updates the whole document instead of only the changed fields.

**Comment by karmi** [comment]
The trouble is that I'd have to play with it in a executable example like this one: https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/examples/activerecord_associations.rb

Thinking about it just theoretically, I think `update_document_attributes` is a better way to go now, and probably in general: you don't have to pass the whole model payload there, via `as_indexed_json`, but only the attributes you're interested in.

(And please definitely invest time in some kind of background indexing... :)

**Comment by karmi** [comment]
@ggcampinho There have been issue with the `update_document` method, but I think those should be solved right now... In the example [`activerecord_associations.rb`](https://github.com/elastic/elasticsearch-rails/blob/master/elasticsearch-model/examples/activerecord_associations.rb), I use `index_document` though, so I might look into that in the future. Or you can play with that example and try to break it, that would help.

The `reindex` method is defined on the instance, right? I think you can just use `index_document` in that case...

**Comment by ggcampinho** [comment]
Thanks! I will test only the `index_document`.

I have the impression that the correct behaviour of the `update_document` is to send the difference between the old and the new result of `as_indexed_json`, which I see is more complex to implement.

**Comment by karmi** [comment]
@ggcampinho I suspect there _might_ be some subtle bug or at least inconsistency when it comes to `update_document` and relationships, since I don't think there's waterproof coverage for that particular case, but it would require too much context switching on my side right now -- I'll try to look into that, though.

**Comment by arjan0307** [comment]
Five years later this problem still persists. Any perspective on a fix?

**Comment by picandocodigo** [comment]
@arjan0307 I will try and have a look at this once I get some time to work on this library.
